language: objective-c

osx_image: xcode6.4

script:
- xcodebuild -project NSDate-Extension\ Example.xcodeproj -scheme NSDate-Extension\ Example -destination "platform=iOS Simulator,name=iPhone 4s,OS=7.1" -configuration Debug clean build test
